name: C/C++ CI

on:
  push:
    branches: [ "main", "Developer" ]
  pull_request:
    branches: [ "main", "Developer" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y valgrind libboost-all-dev nlohmann-json3-dev doctest-dev

    - name: make run_tests
      run: cd SystemFiles && make all && make run_tests


